spring:
  application:
    name: jdbc-template
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
  h2:
    console:
      enabled: true

server:
  port: 8085

